# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: test_data.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'test_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftest_data.proto\x12\ttest_data\"x\n\rKeyValuePairs\x12\x37\n\x08kv_pairs\x18\x01 \x03(\x0b\x32%.test_data.KeyValuePairs.KvPairsEntry\x1a.\n\x0cKvPairsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x19\n\x08\x46latList\x12\r\n\x05items\x18\x01 \x03(\x05\"\x82\x01\n\x0b\x43omplexData\x12&\n\x04info\x18\x01 \x01(\x0b\x32\x18.test_data.KeyValuePairs\x12$\n\x07numbers\x18\x02 \x01(\x0b\x32\x13.test_data.FlatList\x12%\n\x06nested\x18\x03 \x03(\x0b\x32\x15.test_data.NestedData\"&\n\nNestedData\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KEYVALUEPAIRS_KVPAIRSENTRY']._loaded_options = None
  _globals['_KEYVALUEPAIRS_KVPAIRSENTRY']._serialized_options = b'8\001'
  _globals['_KEYVALUEPAIRS']._serialized_start=30
  _globals['_KEYVALUEPAIRS']._serialized_end=150
  _globals['_KEYVALUEPAIRS_KVPAIRSENTRY']._serialized_start=104
  _globals['_KEYVALUEPAIRS_KVPAIRSENTRY']._serialized_end=150
  _globals['_FLATLIST']._serialized_start=152
  _globals['_FLATLIST']._serialized_end=177
  _globals['_COMPLEXDATA']._serialized_start=180
  _globals['_COMPLEXDATA']._serialized_end=310
  _globals['_NESTEDDATA']._serialized_start=312
  _globals['_NESTEDDATA']._serialized_end=350
# @@protoc_insertion_point(module_scope)
